#################################################
# Docker & Docker-Compose Installation Playbook #
#################################################

---
- name: Install Docker & Docker Compose
  hosts: localhost

  tasks:  
    - name: Remove old Docker installations, if any
      become: yes
      apt: 
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd 
          - runc 
        state: absent
  
    - name: Remove Update Upgrade dependencies
      become: yes
      apt: 
          autoremove: yes
          update_cache: yes
          upgrade: yes
    
    - name: Install packages
      become: yes
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg
          - gnupg-agent
          - software-properties-common

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present
        update_cache: yes      

    - name: Install Docker Engine
      become: yes
      apt:         
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Install Docker Compose
      become: yes
      get_url:
        url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose           
        mode: 0755
       
       