################################
# Docker Installation Playbook #
################################

---
- name: Install Docker 
  hosts: all

  tasks:  
    - name: Remove old Docker installations, if any
      become: yes
      apt: 
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd 
          - runc 
        state: absent
  
    - name: Remove Update Upgrade dependencies
      become: yes
      apt: 
          autoremove: yes
          update_cache: yes
          upgrade: yes
    
    - name: Install packages
      become: yes
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - name: Update and install Docker Engine
      become: yes
      apt: 
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
           
